version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: database-mysql-db-1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: database-backend-1
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql-db

  frontend:
    build:
      context: ./frontend
    container_name: database-frontend-1
    ports:
      - "80:80"
