apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-dockerhub-username>/backend:latest
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: db-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: db-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: db-name
          ports:
            - containerPort: 3000
