apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv  # Volume Name
spec:
  capacity:
    storage: 5Gi  # Define Storage Size
  accessModes:
    - ReadWriteOnce  # Available Modes: ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # Options: Retain, Delete, Recycle
  storageClassName: manual  # Must match PVC storageClassName
  volumeMode: Filesystem  # Options: Filesystem, Block
  hostPath:
    path: "/mnt/data"  # Directory on the Node
