apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
data:
  db-host: <base64-encoded-rds-endpoint>
  db-user: cm9vdA==         # base64 encoded 'root'
  db-password: eW5nV0lFNTAw # base64 encoded 'yngWIE500'
  db-name: c2ltcGxlX3Byb2plY3Q= # base64 encoded 'simple_project'
